### ISSUE TITLE
Readme: init db instructiosn fail

### ISSUE THREAD

**Issue by strazto** [Damian-Siderides/Openbook#1]
```fish
flask --app openbook init-db
```

```
Error: While importing 'openbook', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/matty/projects/Openbook/.env/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/Users/matty/projects/Openbook/openbook/__init__.py", line 5, in <module>
    from instance import config
ModuleNotFoundError: No module named 'instance'
```

Output of pip freeze:

```fish
pip freeze 
```

```
blinker==1.8.2
click==8.1.7
Flask==3.0.3
itsdangerous==2.2.0
Jinja2==3.1.4
MarkupSafe==2.1.5
Werkzeug==3.0.3
```

Running `Python 3.12.2`

**Comment by strazto** [comment]
I think its because you've stored your secret key in some ignored python dir `instance`

No idea what this is meant to be

**Comment by strazto** [comment]
Made a file called `instance.py` 
```py
class config:
    SECRET_KEY = "keyboardcat"
```

Looks like u ignore a folder `instance/`, I assume you intended:

```py
# instance/config.py
SECRET_KEY = "keyboardcat"
```

Probably better off using env vars for your app secrets or something. document this
